[Unit]
Requires=watch-assistant-qbittorrent.service
After=watch-assistant-qbittorrent.service

[Service]
Environment=PYTHONPATH=/opt/watch-assistant/current/src
LoadCredential=qbittorrent_username:/etc/watch-assistant-inspection/qbittorrent_username
LoadCredential=qbittorrent_password:/etc/watch-assistant-inspection/qbittorrent_password
