export type UiErrorAction =
  | "retry"
  | "reload_settings"
  | "reauthenticate"
  | "view_task"
  | "refresh_snapshot"
  | "inspect_configuration"
  | "open_library"
  | null;

export interface UiErrorDescriptor {
  code: string;
  title: string;
  message: string;
  suggestion: string;
  retryable: boolean;
  action: UiErrorAction;
}

const RETRYABLE_CODES = new Set([
  "auth_not_configured",
  "backups_unavailable",
  "backup_failed",
  "credential_unavailable",
  "credentials_unavailable",
  "deployment_diagnostics_unavailable",
  "internal_error",
  "manual_import_unavailable",
  "notifications_unavailable",
  "operation_unavailable",
  "organization_plan_unavailable",
  "organization_history_unavailable",
  "organization_preview_unavailable",
  "target_catalog_unavailable",
  "organization_operation_unavailable",
  "organization_reconciliation_unavailable",
  "organization_schedule_unavailable",
  "reconciliation_unavailable",
  "reconciliation_conflict",
  "p115_settings_unavailable",
  "qrcode_provider_unavailable",
  "quality_profiles_unavailable",
  "season_metadata_unavailable",
  "settings_unavailable",
  "subscription_check_failed",
  "subscription_unavailable",
  "tmdb_unavailable",
  "not_found",
  "resource_search_unavailable",
  "resource_search_failed",
  "resource_search_timeout",
  "workflows_unavailable",
  "library_scope_verification_failed",
  "library_scope_unverified",
  "library_scan_unavailable",
  "library_scan_not_found",
  "invalid_library_id",
  "invalid_scan_run_id",
  "invalid_directory_limit",
  "scan_mode_unsupported",
  "checkpoint_invalid",
  "plan_hash_mismatch",
  "empty_directory_cleanup_disabled",
  "empty_directory_cleanup_unavailable",
  "empty_cleanup_expired",
  "empty_cleanup_changed",
  "empty_cleanup_uncertain",
  "empty_cleanup_failed",
  "empty_cleanup_in_progress",
  "small_file_cleanup_in_progress",
  "empty_cleanup_already_applied",
  "empty_cleanup_not_reviewable",
  "empty_cleanup_plan_invalid",
  "directory_ownership_unavailable",
]);

const ACTION_BY_CODE: Record<string, UiErrorAction> = {
  backup_not_found: "retry",
  cache_warm_disabled: "inspect_configuration",
  idempotency_key_conflict: "view_task",
  inspection_not_found: "retry",
  library_configuration_conflict: "reload_settings",
  library_scope_mismatch: "inspect_configuration",
  library_scope_unavailable: "inspect_configuration",
  library_scope_verification_failed: "retry",
  target_catalog_unavailable: "retry",
  inventory_scope_unconfigured: "open_library",
  inventory_index_incomplete: "open_library",
  inventory_index_stale: "open_library",
  inventory_index_unknown: "open_library",
  inventory_exact_duplicate: "open_library",
  inventory_review_required: "open_library",
  lease_claim_lost: "view_task",
  lease_is_not_owned: "view_task",
  operation_is_not_retryable: "view_task",
  strm_library_operation_conflict: "retry",
  strm_operation_in_progress: "retry",
  strm_operation_lease_lost: "view_task",
  operation_not_found: "retry",
  operation_plan_conflict: "retry",
  organization_plan_disabled: "inspect_configuration",
  organization_execution_disabled: "inspect_configuration",
  organization_execution_unavailable: "inspect_configuration",
  organization_write_disabled: "inspect_configuration",
  organization_write_unverified: "inspect_configuration",
  organization_contract_evidence_required: "inspect_configuration",
  capability_unverified: "inspect_configuration",
  contract_unverified: "inspect_configuration",
  organization_lease_required: "refresh_snapshot",
  target_directory_parent_missing: "refresh_snapshot",
  target_directory_create_failed: "view_task",
  organization_reconciliation_unavailable: "retry",
  permanent_delete_disabled: "inspect_configuration",
  permanent_delete_unverified: "inspect_configuration",
  strm_full_disabled: "inspect_configuration",
  strm_incremental_disabled: "inspect_configuration",
  strm_cleanup_disabled: "inspect_configuration",
  cleanup_plan_required: "refresh_snapshot",
  empty_directory_cleanup_disabled: "inspect_configuration",
  small_file_cleanup_unavailable: "retry",
  small_file_threshold_unconfigured: "reload_settings",
  cleanup_snapshot_unavailable: "refresh_snapshot",
  snapshot_stale: "refresh_snapshot",
  empty_directory_cleanup_unavailable: "retry",
  empty_cleanup_expired: "refresh_snapshot",
  empty_cleanup_changed: "refresh_snapshot",
  empty_cleanup_uncertain: "view_task",
  empty_cleanup_failed: "refresh_snapshot",
  empty_cleanup_in_progress: "retry",
  small_file_cleanup_in_progress: "retry",
  empty_cleanup_already_applied: "refresh_snapshot",
  empty_cleanup_not_reviewable: "refresh_snapshot",
  empty_cleanup_plan_invalid: "refresh_snapshot",
  directory_ownership_unavailable: "retry",
  directory_ownership_unrecorded: "view_task",
  plan_already_has_operation: "view_task",
  plan_prerequisites_changed: "reload_settings",
  plan_revision_changed: "reload_settings",
  push_kind_unsupported: "inspect_configuration",
  quality_profile_conflict: "reload_settings",
  quality_profile_not_found: "retry",
  resource_not_found: "refresh_snapshot",
  resource_snapshot_not_found: "refresh_snapshot",
  stale_revision: "reload_settings",
  subscription_conflict: "retry",
  subscription_not_found: "retry",
  task_not_found: "retry",
  uncertain_requires_verification: "view_task",
  reconciliation_unavailable: "retry",
  reconciliation_conflict: "refresh_snapshot",
  task_not_reconcilable: "view_task",
  workflow_not_found: "retry",
  workflow_prerequisite_not_met: "view_task",
  workflow_stage_regression: "view_task",
  workflow_stage_terminal: "view_task",
  workflow_evidence_required: "view_task",
  workflow_discovery_conflict: "refresh_snapshot",
  resource_search_not_found: "retry",
  resource_search_unavailable: "retry",
  resource_search_failed: "retry",
  resource_search_timeout: "retry",
};

const ADDITIONAL_CODES = [
  "auth_not_configured", "auth_unavailable", "internal_error", "not_found", "backup_requires_file_database", "backup_failed", "backup_not_found",
  "backup_manifest_invalid", "backup_database_missing", "invalid_backup_id", "database_not_found",
  "backups_unavailable", "credential_unavailable", "credentials_unavailable", "invalid_credential_request",
  "deployment_diagnostics_unavailable", "manual_import_unavailable", "confirmation_required",
  "resource_conflict", "invalid_resource", "media_mismatch", "invalid_magnet", "unsupported_url",
  "invalid_share_url", "unsupported_share_domain", "season_metadata_unavailable", "season_not_found",
  "season_metadata_cache_invalid", "invalid_series_id", "invalid_season_number", "invalid_language",
  "inspection_not_found", "resource_not_inspectable", "subscription_unavailable", "subscription_not_found",
  "subscription_exists", "subscription_conflict", "subscription_not_pauseable", "subscription_cancelled",
  "subscription_not_active", "subscription_check_failed", "settings_unavailable", "invalid_content_policy",
  "p115_settings_unavailable", "notifications_unavailable", "notification_not_found",
  "notification_preference_conflict", "quality_profiles_unavailable", "quality_profile_not_found",
  "quality_profile_conflict", "invalid_quality_rules", "unknown_quality_rule", "invalid_min_resolution",
  "invalid_filename", "invalid_source_object", "invalid_tmdb_candidate", "tmdb_candidate_not_found", "candidate_target_unavailable", "source_snapshot_mismatch", "organization_plan_disabled", "organization_plan_unavailable", "organization_history_unavailable", "organization_preview_unavailable",
  "target_catalog_unavailable",
  "organization_schedule_unavailable", "source_target_same", "invalid_source_directory_ids", "invalid_source_directory_labels", "invalid_target_directory_id", "invalid_target_directory_label", "invalid_push_directory_id", "invalid_push_directory_label",
  "invalid_video_extensions", "invalid_metadata_extensions",
  "organization_execution_disabled", "organization_execution_unavailable", "organization_write_disabled", "organization_write_unverified", "organization_contract_evidence_required", "contract_unverified", "capability_unverified", "organization_lease_required", "target_directory_create_failed", "target_directory_parent_missing", "permanent_delete_disabled", "permanent_delete_unverified", "delete_unavailable", "strm_full_disabled", "strm_incremental_disabled", "strm_cleanup_disabled", "strm_library_operation_conflict", "strm_operation_in_progress", "strm_operation_lease_lost", "cleanup_plan_required", "cleanup_plan_already_applied", "strm_unavailable", "strm_operation_failed", "strm_operation_cancelled", "strm_operation_recovered", "strm_operation_timeout", "strm_operation_not_found", "strm_operation_not_resumable", "invalid_operation_kind", "invalid_cursor", "invalid_limit", "invalid_operation_timeout", "source_snapshot_not_ready", "source_snapshot_not_current", "strm_output_unavailable", "invalid_playback_url_prefix", "plan_invalid", "cleanup_plan_expired", "cleanup_plan_blocked", "cleanup_plan_changed", "cleanup_plan_not_reviewable", "organization_operation_unavailable", "organization_reconciliation_unavailable", "plan_not_found",
  "invalid_plan", "invalid_pagination", "invalid_revision", "invalid_alias", "stale_revision",
  "plan_not_reviewable", "plan_not_executable", "operation_not_found", "operation_unavailable", "invalid_plan_id",
  "invalid_idempotency_key", "invalid_operation_id", "plan_is_not_planned", "plan_prerequisites_changed",
  "plan_revision_changed", "idempotency_key_conflict", "plan_already_has_operation", "operation_plan_conflict",
  "operation_creation_conflict", "operation_revision_changed", "operation_is_not_cancellable",
  "uncertain_requires_verification", "operation_is_not_claimable", "lease_is_active", "lease_claim_lost",
  "lease_is_not_owned", "operation_is_not_retryable", "invalid_terminal_status", "directory_scope_required",
  "cache_warm_disabled", "cache_warm_running", "resource_not_found", "push_kind_unsupported", "task_not_found",
  "workflow_not_found", "workflows_unavailable", "task_not_reconcilable", "reconciliation_unavailable", "reconciliation_conflict", "season_requires_tv", "invalid_page_size",
  "workflow_conflict", "workflow_not_awaiting_confirmation", "workflow_not_cancellable",
  "workflow_prerequisite_not_met", "workflow_stage_regression", "workflow_stage_terminal", "workflow_evidence_required", "workflow_discovery_conflict",
  "workflow_id_conflict", "high_risk_approval_required", "web_approval_required",
  "resource_snapshot_not_found", "resource_search_not_found", "resource_search_unavailable",
  "resource_search_failed", "invalid_season_request", "library_inventory_incomplete",
  "library_identity_conflict", "library_scan_unavailable", "library_scan_not_found",
  "invalid_library_id", "invalid_scan_run_id", "invalid_directory_limit",
  "scan_mode_unsupported", "checkpoint_invalid", "plan_hash_mismatch", "plan_hash_required",
  "p115_device_unavailable", "p115_directory_out_of_scope", "p115_directory_read_failed",
  "p115_directory_scope_unavailable", "p115_directory_unavailable", "p115_qrcode_save_failed",
  "p115_qrcode_unavailable", "qrcode_provider_unavailable", "qrcode_result_invalid",
  "qrcode_session_not_found", "qrcode_unavailable", "active_device_cannot_revoke",
  "device_not_found", "invalid_page",
  "agent_token_conflict", "agent_token_not_found", "audit_not_found", "forbidden",
  "inspection_unsupported", "invalid_agent_token_request", "invalid_request",
  "inventory_check_failed", "inventory_exact_duplicate", "inventory_index_incomplete",
  "inventory_index_stale", "inventory_index_unknown", "inventory_review_required",
  "inventory_scope_unconfigured", "library_not_found", "mcp_unavailable", "media_not_found",
  "method_not_found", "missing_scope", "needs_auth", "pansou_unavailable", "prowlarr_settings_unavailable",
  "invalid_prowlarr_settings", "prowlarr_disabled", "prowlarr_not_configured", "prowlarr_auth_required",
  "prowlarr_invalid_response", "prowlarr_unavailable",
  "plan_digest_mismatch", "plan_digest_required", "pwa_device_conflict", "pwa_device_not_found",
  "pwa_subscription_invalid", "pwa_unavailable", "rate_limited", "request_failed",
  "resource_forbidden", "resource_search_timeout", "settings_conflict", "task_not_retryable", "task_not_cancellable",
  "tmdb_unavailable", "tool_not_found", "unauthorized", "uncertain", "validation_error",
  "library_configuration_conflict", "library_scope_mismatch", "library_scope_unavailable",
  "library_scope_verification_failed",
  "library_scope_unverified",
  "empty_directory_cleanup_disabled",
  "empty_directory_cleanup_unavailable",
  "empty_cleanup_expired",
  "empty_cleanup_changed",
  "empty_cleanup_uncertain",
  "empty_cleanup_failed",
  "empty_cleanup_in_progress",
  "small_file_cleanup_in_progress",
  "empty_cleanup_already_applied",
  "empty_cleanup_not_reviewable",
  "empty_cleanup_plan_invalid",
  "cleanup_scope_unverified", "directory_ownership_unavailable", "directory_ownership_unrecorded",
  "invalid_playback_request", "strm_playback_disabled", "strm_playback_unverified",
  "strm_playback_unavailable", "playback_file_not_found", "playback_network_forbidden",
  "playback_timeout", "playback_remote_failed",
  "webhook_conflict", "webhook_delivery_conflict", "webhook_delivery_not_found",
  "webhook_dns_failed", "webhook_event_not_allowed", "webhook_not_found",
  "webhook_url_not_allowed", "webhook_url_unresolvable", "webhooks_unavailable",
  // 后端 api_errors._CATALOG 补充注册的既有错误码(见后端 L3 修复),
  // 与后端保持一致并满足前后端目录契约测试。
  "candidate_search_unavailable", "candidate_source_required", "invalid_candidate_limit",
  "invalid_candidate_query", "invalid_lease_duration", "invalid_source_index",
  "invalid_workflow_id", "no_video_files", "plan_expired", "scan_cancel_failed",
  "scan_entry_invalid", "scan_in_progress", "scan_not_current", "scan_not_found",
  "source_directory_not_found", "source_scope_unverified", "source_target_overlap",
  "workflow_id_conflict", "workflow_stage_missing",
  // H9: 后端 _CATALOG 新增注册的 STRM/target/device/settings 错误码，
  // 与后端保持一致并满足前后端目录契约测试。
  "strm_operation_claim_conflict", "strm_operation_creation_conflict", "strm_operation_lease_required",
  "strm_operation_not_reconcilable", "strm_operation_not_running", "strm_full_failed",
  "strm_incremental_failed", "strm_cleanup_failed", "invalid_cursor", "invalid_limit",
  "task_lease_active", "webhook_endpoint_disabled", "device_unavailable", "invalid_device_code",
  "invalid_device_name", "invalid_small_file_threshold", "target_file_invalid", "invalid_poll_interval",
  "invalid_conflict_mode", "invalid_scan_interval_minutes",
  "target_directory_id_invalid", "target_directory_limit_invalid", "target_file_limit_invalid",
  "target_directory_incomplete", "target_file_limit_exceeded", "target_file_name_invalid",
  "target_file_identity_conflict", "target_directory_name_invalid", "target_directory_path_conflict",
  "target_directory_identity_conflict", "target_directory_limit_exceeded",
  "target_directory_pagination_unverified", "target_entry_type_unverified", "target_entry_scope_unverified",
  "target_entry_identity_unverified", "target_directory_read_failed",
] as const;

function additionalDescriptor(code: string): Omit<UiErrorDescriptor, "code"> {
  const retryable = RETRYABLE_CODES.has(code);
  return {
    title: "操作暂时无法完成",
    message: "本次操作未完成，当前页面没有更新。",
    suggestion: retryable ? "请稍后重试。" : "请检查当前状态后再试。",
    retryable,
    action: ACTION_BY_CODE[code] ?? (retryable ? "retry" : null),
  };
}

const CATALOG: Record<string, Omit<UiErrorDescriptor, "code">> = {
  ...Object.fromEntries(ADDITIONAL_CODES.map((code) => [code, additionalDescriptor(code)])),
  notify_channels_unavailable: { title: "通知渠道服务暂时不可用", message: "本次通知渠道操作未完成。", suggestion: "请稍后重试。", retryable: true, action: "retry" },
  notify_channel_not_found: { title: "通知渠道不存在", message: "本次通知渠道操作未完成。", suggestion: "请刷新渠道列表后再试。", retryable: false, action: "retry" },
  unsupported_notify_kind: { title: "不支持的通知渠道类型", message: "本次通知渠道未保存。", suggestion: "当前仅支持飞书机器人。", retryable: false, action: "reload_settings" },
  tmdb_unavailable: { title: "影视信息暂时无法加载", message: "本次影视资料没有更新，资源区和已有页面仍可查看。", suggestion: "请重新加载影视资料。", retryable: true, action: "retry" },
  rate_limited: { title: "请求过于频繁", message: "本次请求未执行，当前页面内容没有改变。", suggestion: "请稍后再试。", retryable: true, action: "retry" },
  plan_prerequisites_changed: { title: "整理计划已失效", message: "扫描快照已更新，本次整理未执行。", suggestion: "请重新扫描并生成新的整理计划后再确认。", retryable: false, action: "reload_settings" },
  organization_contract_evidence_required: { title: "整理写入缺少契约证据", message: "本次 115 写入操作未执行。", suggestion: "环境开关不能代替契约验收，请先提供独立的契约验收证据。", retryable: false, action: "inspect_configuration" },
  organization_execution_unavailable: { title: "整理执行能力暂不可用", message: "本次整理操作未排队，也未执行远端写入。", suggestion: "请检查 115 readiness、整理写入契约和后台 worker 后再试。", retryable: false, action: "inspect_configuration" },
  cleanup_scope_unverified: { title: "空目录归属范围未验证", message: "本次空目录清理未执行，系统没有足够的持久化归属证据。", suggestion: "请重新完成整理目录登记和媒体库扫描。", retryable: false, action: "refresh_snapshot" },
  directory_ownership_unavailable: { title: "归档目录归属记录不可用", message: "本次目标目录没有创建，系统无法建立持久化归属证据。", suggestion: "请检查数据库迁移和整理状态后重试。", retryable: true, action: "retry" },
  directory_ownership_unrecorded: { title: "归档目录归属记录缺失", message: "远端目录写入结果待核对，系统不会自动重复创建。", suggestion: "请先核对 115 远端目录和本地整理记录。", retryable: false, action: "view_task" },
  organization_lease_required: { title: "整理操作租约无效", message: "本次目标目录没有创建。", suggestion: "请从已确认的整理操作重新执行，系统不会在预览阶段创建目录。", retryable: false, action: "refresh_snapshot" },
  target_directory_create_failed: { title: "归档目录创建失败", message: "本次目标目录没有完成创建。", suggestion: "请先核对 115 远端目录状态，再决定是否重新执行。", retryable: false, action: "view_task" },
  target_directory_parent_missing: { title: "归档目录父级不存在", message: "本次目标目录没有创建。", suggestion: "请确认整理计划和目标目录范围后重新生成计划。", retryable: false, action: "refresh_snapshot" },
  cleanup_plan_required: { title: "需要先确认 STRM 清理计划", message: "本次清理没有执行任何退休操作。", suggestion: "请打开清理预览，核对候选后再确认执行。", retryable: false, action: "refresh_snapshot" },
  strm_library_operation_conflict: { title: "STRM 媒体库操作冲突", message: "本次 STRM 操作未开始，避免并发修改媒体库清单。", suggestion: "请等待当前操作完成后再重试。", retryable: true, action: "retry" },
  strm_operation_in_progress: { title: "STRM 操作正在执行", message: "本次请求未重复执行。", suggestion: "请稍后刷新操作状态。", retryable: true, action: "retry" },
  strm_operation_lease_lost: { title: "STRM 操作执行权已变化", message: "旧执行已停止继续更新文件或状态。", suggestion: "请查看操作状态，确认结果后再决定是否重试。", retryable: false, action: "view_task" },
  operation_plan_conflict: { title: "计划已有整理操作", message: "本次没有重复创建整理操作。", suggestion: "请查看该计划关联的操作状态。", retryable: false, action: "view_task" },
  outcome_unknown: { title: "暂时无法确认整理结果", message: "远端结果暂时无法确认，请先核对 115 当前状态，不要重复提交。", suggestion: "请核对 115 目录与本地整理记录后再决定下一步。", retryable: false, action: "view_task" },
  remote_write_failed: { title: "远端写入失败", message: "远端写入失败，请核对 115 目录状态后再决定是否重试。", suggestion: "请核对 115 远端目录与本地整理记录，确认写入结果后再重试。", retryable: false, action: "view_task" },
  target_root_changed: { title: "整理目标目录已变更", message: "整理目标目录已变更，当前计划需要重新确认。", suggestion: "请重新确认整理目标目录与当前计划后再提交。", retryable: false, action: "reload_settings" },
  settings_conflict: { title: "设置已在其他位置更新", message: "本次修改未保存，当前页面不是最新版本。", suggestion: "请加载最新设置后重新提交。", retryable: false, action: "reload_settings" },
  credential_rejected: { title: "凭据验证未通过", message: "新凭据未生效，原配置保持不变。", suggestion: "请检查凭据后重新验证。", retryable: false, action: "reauthenticate" },
  credential_validation_unavailable: { title: "暂时无法验证凭据", message: "本次验证未完成，原配置保持不变。", suggestion: "请稍后重新验证。", retryable: true, action: "retry" },
  credentials_unavailable: { title: "连接配置暂时不可用", message: "连接配置没有更新。", suggestion: "请稍后重新加载配置。", retryable: true, action: "retry" },
  resource_snapshot_not_found: { title: "资源列表已更新", message: "当前分页快照已失效，影视资料没有受到影响。", suggestion: "请返回第一页刷新资源。", retryable: true, action: "refresh_snapshot" },
  inspection_unsupported: { title: "当前环境无法检测资源", message: "未创建资源检测任务。", suggestion: "请查看资源检测配置。", retryable: false, action: "inspect_configuration" },
  task_not_retryable: { title: "当前任务不能直接重试", message: "原任务状态未改变。", suggestion: "请查看任务状态后再决定下一步。", retryable: false, action: "view_task" },
  task_not_cancellable: { title: "当前任务不能取消", message: "任务状态未改变，远端结果不会被伪造撤回。", suggestion: "请查看任务状态；如果远端结果不确定，请先核对后再决定下一步。", retryable: false, action: "view_task" },
  needs_auth: { title: "115 登录状态已失效", message: "任务尚未继续提交到 115。", suggestion: "请前往凭据设置重新登录。", retryable: false, action: "reauthenticate" },
  uncertain: { title: "暂时无法确认提交结果", message: "远端可能已经接受，系统不会自动重复提交。", suggestion: "请查看任务状态，确认前不要重复操作。", retryable: false, action: "view_task" },
  invalid_credentials: { title: "登录信息不正确", message: "本次登录未成功。", suggestion: "请检查后重新登录。", retryable: true, action: "retry" },
  auth_not_configured: { title: "登录服务暂时不可用", message: "本次登录未执行。", suggestion: "请稍后重试或联系管理员。", retryable: true, action: "retry" },
  resource_not_found: { title: "资源不存在", message: "本次任务未创建，资源可能已被移除。", suggestion: "请刷新资源列表后再试。", retryable: false, action: "refresh_snapshot" },
  push_kind_unsupported: { title: "当前资源类型不可推送", message: "本次任务未创建，当前环境不支持该资源类型。", suggestion: "请查看 115 推送能力配置。", retryable: false, action: "inspect_configuration" },
  workflow_not_found: { title: "关联工作流不存在", message: "本次任务未创建。", suggestion: "请刷新页面后重新操作。", retryable: false, action: "retry" },
  high_risk_approval_required: { title: "需要 Web 人工批准", message: "影响数量超过阈值，本次整理未排队。", suggestion: "请在任务中心完成人工批准后再提交。", retryable: false, action: "view_task" },
  web_approval_required: { title: "需要 Web 人工批准", message: "Agent 不能直接批准高风险计划。", suggestion: "请使用已登录的 Web 会话完成批准。", retryable: false, action: "view_task" },
  workflow_id_conflict: { title: "任务已关联其他工作流", message: "本次任务未改动现有关联。", suggestion: "请查看原工作流或创建新的搜索任务。", retryable: false, action: "view_task" },
  workflow_conflict: { title: "工作流状态发生冲突", message: "本次工作流操作未执行。", suggestion: "请刷新工作流状态后再试。", retryable: false, action: "reload_settings" },
  workflow_not_awaiting_confirmation: { title: "工作流当前不需要确认", message: "本次确认未执行。", suggestion: "请查看当前阶段状态后再操作。", retryable: false, action: "view_task" },
  workflow_not_cancellable: { title: "工作流当前不可取消", message: "本次取消未执行，运行中或远端结果不会被伪造撤回。", suggestion: "请先查看工作流阶段和远端任务状态。", retryable: false, action: "view_task" },
  workflow_prerequisite_not_met: { title: "工作流前置阶段未完成", message: "本次阶段没有开始，系统保持阶段顺序。", suggestion: "请先完成前置阶段后再继续。", retryable: false, action: "view_task" },
  workflow_stage_regression: { title: "工作流阶段不能回退", message: "本次阶段更新未保存，已有结果保持不变。", suggestion: "请刷新任务中心查看当前阶段。", retryable: false, action: "view_task" },
  workflow_stage_terminal: { title: "工作流阶段已结束", message: "本次阶段更新未保存，系统不会改写已结束结果。", suggestion: "请查看诊断信息并核对关联任务。", retryable: false, action: "view_task" },
  organization_schedule_unavailable: { title: "自动整理服务未启动", message: "当前环境没有启动自动整理调度服务，整理任务尚未执行。", suggestion: "请在部署配置中启用整理计划服务后再试。", retryable: true, action: "inspect_configuration" },
  library_inventory_incomplete: { title: "库存索引不完整", message: "本次库存身份确认未保存。", suggestion: "请先完成一次完整库存扫描。", retryable: false, action: "refresh_snapshot" },
  library_identity_conflict: { title: "库存身份已变化", message: "本次库存身份确认未保存。", suggestion: "请刷新库存后重新确认。", retryable: false, action: "refresh_snapshot" },
  inventory_scope_unconfigured: { title: "未配置 115 媒体库范围", message: "本次推送未提交到 115，系统还没有可核对的媒体库库存范围。", suggestion: "请前往“媒体库”配置生产根目录，验证范围并完成一次完整扫描后再重试。", retryable: false, action: "open_library" },
  inventory_index_incomplete: { title: "115 媒体库库存未完成", message: "本次推送未提交到 115，系统无法确认媒体库中是否已有该资源。", suggestion: "请前往“媒体库”完成一次完整扫描后再重试。", retryable: false, action: "open_library" },
  inventory_index_stale: { title: "115 媒体库库存已过期", message: "本次推送未提交到 115，当前库存索引不能作为去重依据。", suggestion: "请前往“媒体库”重新扫描库存后再重试。", retryable: false, action: "open_library" },
  inventory_index_unknown: { title: "115 媒体库库存状态未知", message: "本次推送未提交到 115，当前库存扫描状态不可靠。", suggestion: "请前往“媒体库”确认扫描状态并重新扫描后再重试。", retryable: false, action: "open_library" },
  inventory_exact_duplicate: { title: "资源已在 115 媒体库中", message: "本次推送未提交到 115，库存中已经存在相同资源。", suggestion: "请前往“媒体库”查看现有资源，不要重复提交。", retryable: false, action: "open_library" },
  inventory_review_required: { title: "115 媒体库存在待确认候选", message: "库存存在仅凭文件名匹配的相近资源，本次检查未阻止推送。", suggestion: "可前往“媒体库”查看匹配依据，再按质量策略或人工确认处理。", retryable: false, action: "open_library" },
  // H9: 与后端 _CATALOG 新增注册码保持一致
  strm_operation_claim_conflict: { title: "STRM 操作正在执行", message: "本次请求未重复执行，同类操作仍在运行。", suggestion: "请稍后刷新操作状态，等待当前操作完成后再试。", retryable: true, action: "retry" },
  strm_operation_creation_conflict: { title: "STRM 操作创建冲突", message: "本次操作未创建，同类操作已存在。", suggestion: "请刷新操作列表，等待现有操作完成后再试。", retryable: true, action: "retry" },
  strm_operation_lease_required: { title: "需要 STRM 操作执行权", message: "本次操作未执行，缺少有效的执行租约。", suggestion: "请从操作详情重新发起，或等待执行权恢复后再试。", retryable: false, action: "view_task" },
  strm_operation_not_reconcilable: { title: "STRM 操作无法核对", message: "本次只读核对未执行，操作没有可核对的远端标识。", suggestion: "请查看操作状态；只有已取得远端标识的操作才能核对。", retryable: false, action: "view_task" },
  strm_operation_not_running: { title: "STRM 操作未在运行", message: "本次操作未执行，当前操作不在运行状态。", suggestion: "请查看操作当前状态后重试。", retryable: false, action: "view_task" },
  strm_full_failed: { title: "STRM 全量生成失败", message: "本次全量生成未完成，文件没有全部更新。", suggestion: "请查看失败明细后重新生成。", retryable: true, action: "retry" },
  strm_incremental_failed: { title: "STRM 增量生成失败", message: "本次增量生成未完成，文件没有全部更新。", suggestion: "请查看失败明细后重新生成。", retryable: true, action: "retry" },
  strm_cleanup_failed: { title: "STRM 清理失败", message: "本次清理未完成，部分文件未清理。", suggestion: "请查看失败明细后重新清理。", retryable: true, action: "retry" },
  small_file_cleanup_unavailable: { title: "小文件清理服务暂时不可用", message: "本次小文件清理没有执行，远端状态没有被伪造更新。", suggestion: "请检查 115 登录状态和整理写权限配置后重试。", retryable: true, action: "retry" },
  small_file_threshold_unconfigured: { title: "小文件阈值未配置", message: "本次小文件清理未生成预览。", suggestion: "请先在自动整理设置中配置小文件大小阈值。", retryable: false, action: "reload_settings" },
  small_file_cleanup_in_progress: { title: "小文件清理正在执行", message: "本次请求未重复执行小文件回收。", suggestion: "请等待当前清理完成后刷新操作状态。", retryable: true, action: "retry" },
  cleanup_snapshot_unavailable: { title: "清理快照不可用", message: "本次清理未执行，缺少当前完整的扫描快照。", suggestion: "请先完成一次完整扫描后再试。", retryable: true, action: "refresh_snapshot" },
  snapshot_stale: { title: "清理快照已过期", message: "本次清理未执行，快照与当前媒体库不一致。", suggestion: "请重新扫描并刷新快照后重试。", retryable: false, action: "refresh_snapshot" },
  task_lease_active: { title: "任务执行权仍有效", message: "任务仍在运行，本次操作未执行。", suggestion: "请等待任务完成或取消后再试。", retryable: false, action: "view_task" },
  webhook_endpoint_disabled: { title: "Webhook 端点已停用", message: "本次投递未发送，端点当前处于停用状态。", suggestion: "请先在设置中启用该端点。", retryable: false, action: "reload_settings" },
  device_unavailable: { title: "登录设备服务暂时不可用", message: "本次设备操作未完成。", suggestion: "请稍后重试。", retryable: true, action: "retry" },
  invalid_device_code: { title: "设备代码无效", message: "本次设备操作未执行。", suggestion: "请检查设备代码后重试。", retryable: false, action: null },
  invalid_device_name: { title: "设备名称无效", message: "本次设备操作未执行。", suggestion: "请检查设备名称后重试。", retryable: false, action: null },
  invalid_small_file_threshold: { title: "小文件阈值无效", message: "本次整理预览未生成。", suggestion: "请检查小文件阈值设置后重试。", retryable: false, action: "reload_settings" },
  target_file_invalid: { title: "目标文件无效", message: "本次目标文件未处理。", suggestion: "请检查目标文件后再试。", retryable: false, action: null },
  invalid_poll_interval: { title: "轮询间隔无效", message: "本次设置未保存。", suggestion: "请调整轮询间隔后重试。", retryable: false, action: "reload_settings" },
  invalid_conflict_mode: { title: "冲突处理方式无效", message: "本次设置未保存。", suggestion: "请选择有效的冲突处理方式后重试。", retryable: false, action: "reload_settings" },
  invalid_scan_interval_minutes: { title: "扫描间隔无效", message: "本次设置未保存。", suggestion: "请调整扫描间隔后重试。", retryable: false, action: "reload_settings" },
  target_directory_id_invalid: { title: "目标目录标识无效", message: "本次目标目录未读取。", suggestion: "请检查整理计划的目标目录配置。", retryable: false, action: "reload_settings" },
  target_directory_limit_invalid: { title: "目标目录数量上限无效", message: "本次目标目录未读取。", suggestion: "请检查目标目录数量限制配置。", retryable: false, action: "reload_settings" },
  target_file_limit_invalid: { title: "目标文件数量上限无效", message: "本次目标文件未读取。", suggestion: "请检查目标文件数量限制配置。", retryable: false, action: "reload_settings" },
  target_directory_incomplete: { title: "目标目录读取不完整", message: "本次目标目录未完整读取，无法继续。", suggestion: "请稍后重新读取目标目录。", retryable: true, action: "retry" },
  target_file_limit_exceeded: { title: "目标文件数量超限", message: "目标目录文件过多，本次未继续。", suggestion: "请减少目标目录文件或分批处理。", retryable: false, action: null },
  target_file_name_invalid: { title: "目标文件名无效", message: "本次目标文件未读取。", suggestion: "请检查目标文件名。", retryable: false, action: null },
  target_file_identity_conflict: { title: "目标文件身份冲突", message: "本次目标文件读取不一致。", suggestion: "请重新读取目标目录。", retryable: true, action: "retry" },
  target_directory_name_invalid: { title: "目标目录名无效", message: "本次目标目录未读取。", suggestion: "请检查目标目录名。", retryable: false, action: null },
  target_directory_path_conflict: { title: "目标目录路径冲突", message: "本次目标目录读取不一致。", suggestion: "请重新读取目标目录。", retryable: true, action: "retry" },
  target_directory_identity_conflict: { title: "目标目录身份冲突", message: "本次目标目录读取不一致。", suggestion: "请重新读取目标目录。", retryable: true, action: "retry" },
  target_directory_limit_exceeded: { title: "目标目录数量超限", message: "目标目录数量过多，本次未继续。", suggestion: "请减少目标目录或分批处理。", retryable: false, action: null },
  target_directory_pagination_unverified: { title: "目标目录分页未验证", message: "目标目录读取可能不完整。", suggestion: "请稍后重新读取目标目录。", retryable: true, action: "retry" },
  target_entry_type_unverified: { title: "目标条目类型未验证", message: "目标条目读取不完整。", suggestion: "请稍后重新读取目标目录。", retryable: true, action: "retry" },
  target_entry_scope_unverified: { title: "目标条目范围未验证", message: "目标条目超出受管范围。", suggestion: "请检查整理范围配置后重试。", retryable: false, action: "reload_settings" },
  target_entry_identity_unverified: { title: "目标条目身份未验证", message: "目标条目读取不完整。", suggestion: "请稍后重新读取目标目录。", retryable: true, action: "retry" },
  target_directory_read_failed: { title: "目标目录读取失败", message: "本次未读取到可靠的目标目录内容。", suggestion: "请检查 115 登录状态后重试。", retryable: true, action: "retry" },
  invalid_cursor: { title: "翻页游标无效", message: "本次列表未加载。", suggestion: "请刷新列表后重新翻页。", retryable: false, action: null },
  invalid_limit: { title: "每页数量无效", message: "本次列表未加载。", suggestion: "请调整每页数量后重试。", retryable: false, action: null },
};

export const UI_ERROR_CODES = Object.freeze(Object.keys(CATALOG));

export function describeUiError(code: string | undefined, status = 0): UiErrorDescriptor {
  const safeCode = typeof code === "string" && /^[a-z][a-z0-9_.-]{1,99}$/.test(code) ? code : "unknown_error";
  const known = CATALOG[safeCode];
  if (known) return { code: safeCode, ...known };
  const retryable = status === 408 || status === 429 || status >= 500;
  return {
    code: safeCode,
    title: "操作暂时无法完成",
    message: "本次操作未完成，当前页面没有更新。",
    suggestion: retryable ? "请稍后重试；如果问题持续，请提供诊断信息。" : "请检查输入和当前状态后再试。",
    retryable,
    action: retryable ? "retry" : null,
  };
}

export function taskErrorMessage(code: string | null): string | null {
  if (!code) return null;
  const descriptor = describeUiError(code);
  return `${descriptor.title}：${descriptor.message}${descriptor.suggestion ? ` ${descriptor.suggestion}` : ""}`;
}
