export const p115DeviceOptions = [
  { value: "android", label: "115生活(Android端)" },
  { value: "115android", label: "115(Android端)" },
  { value: "web", label: "网页版" },
  { value: "ios", label: "115生活(iOS端)" },
  { value: "115ios", label: "115(iOS端)" },
  { value: "ipad", label: "115生活(iPad端)" },
  { value: "115ipad", label: "115(iPad端)" },
  { value: "os_linux", label: "Linux端" },
  { value: "os_windows", label: "Windows端" },
  { value: "os_mac", label: "macOS端" },
  { value: "tv", label: "115网盘(Android电视端)" },
  { value: "apple_tv", label: "115网盘(Apple TV端)" },
  { value: "qandroid", label: "115管理(Android端)" },
  { value: "qios", label: "115管理(iOS端)" },
  { value: "qipad", label: "115管理(iPad端)" },
  { value: "alipaymini", label: "115生活(支付宝小程序)" },
  { value: "wechatmini", label: "115生活(微信小程序)" },
  { value: "harmony", label: "115(鸿蒙端)" },
] as const;
